export const sample_foods = [
  {
    id: '1',
    name: 'Head Kid',
    publishYear: '2015',
    price: 13,
    favorite: true,
    authors: ['David Baddiel'],
    stars: 4.5,
    imageUrl: 'food-1.jpg',
    tags: ['story', 'short story', 'nightmare'],
  },
  {
    id: '2',
    name: 'Harry potter',
    publishYear: '2007',
    price: 16,
    favorite: false,
    authors: ['J K Rowling'],
    stars: 4.5,
    imageUrl: 'food-2.jpg',
    tags: ['story', 'fiction', 'nightmare'],
  },
  {
    id: '3',
    name: 'The story book knight',
    publishYear: '2011',
    price: 10,
    favorite: true,
    authors: ['Helen Docherty','Thomas Docherty'],
    stars: 2.5,
    imageUrl: 'food-3.jpg',
    tags: ['story', 'short story', 'happystory'],
  },
  {
    id: '4',
    name: 'Stuart Little',
    publishYear: '2005',
    price: 10,
    favorite: false,
    authors: ['Carth Williom'],
    stars: 4.5,
    imageUrl: 'food-4.jpg',
    tags: ['story', 'short story', 'fiction'],
  },
  {
    id:'5',
    name: 'The 3 mistakes of my life',
    author: '2009',
    price: 12,
    favorite: false,
    authors: ['chetan bhagat'],
    stars: 4.0,
    imageUrl: 'food-5.jpg',
    tags: ['story', 'sad story'],
  },
  {
    id:'6',
    name: 'Akbar birbal',
    publishYear: '2002',
    price: 10,
    favorite: false,
    authors: ['unknown'],
    stars: 3.5,
    imageUrl: 'food-6.jpg',
    tags: ['horror','sad story', 'fiction','story'],
  },
];

export const sample_tags = [
  { name: 'All', count: 6 },
  { name: 'story', count: 4 },
  { name: 'sad story', count: 2 },
  { name: 'nightmare', count: 3 },
  { name: 'happystory', count: 2 },
  { name: 'short story', count: 1 },
  { name: 'horror ', count: 1 },
  { name: 'fiction', count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@gmail.com',
    password: '12345',
    address: 'Toronto On',
    isAdmin: false,
  },
  {
    id: 2,
    name: 'Jane Doe',
    email: 'jane@gmail.com',
    password: '12345',
    address: 'Shanghai',
    isAdmin: true,
  },
];
